# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Markdown Sitemap
email: ancona.lauren@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simple sitemap generation in markdown with Jekyll & Slickmap CSS 
baseurl: "/markdown-sitemap" # the subpath of your site, e.g. /blog
url: "https://laurenancona.com" # the base hostname & protocol for your site
twitter_username: laurenancona
github_username:  laurenancona

# Build settings
markdown: kramdown

# Enable Github-flavored markdown
kramdown:
  input: GFM

# Number of columns in sitemap
columns: 4
